### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by danieljausovec** [samkitano/stats#1]
I use this code and get this error. What i doing wrong?

$file   = '052015.domain.com';
$data = Stats::Read($file);
$general    = $data->General();

**Comment by samkitano** [comment]
Sorry, there are several bugs in the package, and will need to make a major upgrade, perhaps by the end of the week.

However, you can try this:

$data = App::make('stats');
$data ->Read("awstats$month$year.$host");

Don't forget to set your host's username in the configuration file:

'AWstats_path' => '/home/USER/tmp/awstats/',

**Comment by danieljausovec** [comment]
Thanks. This works.

**Comment by samkitano** [comment]
I've made some fixes, and updated the usage instructions. Could you please run composer update and check if the methods are working for you? I would appreciate it.

for example:

``` php
$file = 'awstats052015.domain.com';
$general = Stats::General($file);
$all = Stats::Read($file);
```

**Comment by danieljausovec** [comment]
I had updated and try this example and works great! Thanks for answer and update.

**Comment by samkitano** [comment]
Thank you Daniel.
