### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by danieljausovec** [samkitano/stats#2]
Hi.

Works this plugin on Laravel 5.1?

**Comment by samkitano** [comment]
I'm afraid it doesn't, and I'm not planning to upgrade it in a near future, as there are plenty of stats trackers out there.

Check this one out:

https://github.com/antonioribeiro/tracker

Thanks for your interest, anyway!

**Comment by danieljausovec** [comment]
Ok. Thanks.
